# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vishu's Pensieve
tagline:          My Pensieve
url:              http://vishu.me
paginate:         1
baseurl:          /
author:
  name:           Vish Vuggumudi
  url:            https://twitter.com/vishvuggumudi
  email:          vuggu001@d.umn.edu
  
# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole
